#ifndef __FTPGC__TYPES_
#define __FTPGC__TYPES_

#define FTPGC_NONETWORK -1
#define FTPGC_NOSOCKET -2
#define FTPGC_NOSOCKETBIND -3
#define FTPGC_NOCONTROL -4
#define FTPGC_SOCKETERROR -5
#define FTPGC_CONTROLALREADYCREATED -6
#define FTPGC_DATAALREADYCREATED -7
#define FTPGC_CONTROLNOTRUNNING -8
#define FTPGC_DATANOTRUNNING -9
#define FTPGC_CONTROLTHREADERROR -10
#define FTPGC_DATATHREADERROR -11
#define FTPGC_THREADERROR -12
#define FTPGC_SUCCESS 1

#endif
